-- ==============================================================================
-- DATAMEX COLLEGE OF SAINT ADELINE (DCSA) - SUPABASE POSTGRESQL SCHEMA
-- Human Action: Copy this entire SQL and paste into Supabase > SQL Editor > Run
-- System Architect: Marcial Lawrence Jr V. Caronan
-- ==============================================================================

-- 1. CLEANUP EXISTING TABLES (IF ANY)
DROP TABLE IF EXISTS employee_benefits CASCADE;
DROP TABLE IF EXISTS attendance CASCADE;
DROP TABLE IF EXISTS payroll CASCADE;
DROP TABLE IF EXISTS feedback CASCADE;
DROP TABLE IF EXISTS announcements CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS benefits_deductions CASCADE;
DROP TABLE IF EXISTS benefits CASCADE;
DROP TABLE IF EXISTS training CASCADE;
DROP TABLE IF EXISTS employees CASCADE;

-- 2. CREATE EMPLOYEES TABLE
CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "employeeNo" VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    "firstName" VARCHAR(100) NOT NULL,
    "lastName" VARCHAR(100) NOT NULL,
    "middleName" VARCHAR(100) DEFAULT '',
    "birthDay" DATE DEFAULT '1997-08-30',
    "birthPlace" VARCHAR(255) DEFAULT 'Metro Manila',
    address TEXT DEFAULT '',
    email VARCHAR(150) UNIQUE NOT NULL,
    gender VARCHAR(20) DEFAULT 'male',
    "civilStatus" VARCHAR(50) DEFAULT 'single',
    nationality VARCHAR(50) DEFAULT 'Filipino',
    religion VARCHAR(50) DEFAULT 'Roman Catholic',
    "phoneNumber" VARCHAR(50) DEFAULT '',
    "sssNumber" VARCHAR(50) DEFAULT '',
    "pagibigNumber" VARCHAR(50) DEFAULT '',
    "tinNumber" VARCHAR(50) DEFAULT '',
    "philhealthNumber" VARCHAR(50) DEFAULT '',
    "bankAccount" VARCHAR(50) DEFAULT '',
    "accountType" VARCHAR(20) DEFAULT 'employee', -- 'admin' or 'employee'
    department VARCHAR(100) DEFAULT 'Information Technology',
    role VARCHAR(150) DEFAULT 'Staff Member',
    "dailyRate" DECIMAL(10,2) DEFAULT 695.00,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. CREATE ATTENDANCE TABLE
CREATE TABLE attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "employeeNo" VARCHAR(50) NOT NULL REFERENCES employees("employeeNo") ON DELETE CASCADE,
    date DATE NOT NULL,
    time_in TIME,
    time_out TIME,
    working_hours DECIMAL(5,2) DEFAULT 0.00,
    late_minutes INT DEFAULT 0,
    overtime_hours DECIMAL(5,2) DEFAULT 0.00,
    status VARCHAR(50) DEFAULT 'Recorded',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. CREATE PAYROLL TABLE
CREATE TABLE payroll (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "employeeNo" VARCHAR(50) NOT NULL REFERENCES employees("employeeNo") ON DELETE CASCADE,
    pay_period_start DATE,
    pay_period_end DATE,
    "ratePerHour" DECIMAL(10,2) DEFAULT 0.00,
    "hoursWorked" DECIMAL(10,2) DEFAULT 0.00,
    regular_days DECIMAL(10,2) DEFAULT 0.00,
    "grossPay" DECIMAL(10,2) DEFAULT 0.00,
    deductions DECIMAL(10,2) DEFAULT 0.00,
    "netPay" DECIMAL(10,2) DEFAULT 0.00,
    "payDate" DATE DEFAULT CURRENT_DATE,
    "lateDeductions" DECIMAL(10,2) DEFAULT 0.00,
    overtime DECIMAL(10,2) DEFAULT 0.00,
    overtime_hours DECIMAL(10,2) DEFAULT 0.00,
    "regularHolidayPay" DECIMAL(10,2) DEFAULT 0.00,
    regular_holiday_days DECIMAL(10,2) DEFAULT 0.00,
    "specialHolidayPay" DECIMAL(10,2) DEFAULT 0.00,
    special_holiday_days DECIMAL(10,2) DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. CREATE ANNOUNCEMENTS TABLE
CREATE TABLE announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    image_path VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. CREATE EVENTS TABLE
CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name VARCHAR(255) NOT NULL,
    event_date DATE NOT NULL,
    event_location VARCHAR(255) NOT NULL,
    image_path VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. CREATE FEEDBACK TABLE
CREATE TABLE feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feedback_text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. CREATE BENEFITS TABLE
CREATE TABLE benefits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    benefit_title VARCHAR(255) NOT NULL,
    benefit_details TEXT NOT NULL,
    image_path VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. CREATE BENEFITS DEDUCTIONS TABLE
CREATE TABLE benefits_deductions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    benefit_name VARCHAR(255) NOT NULL,
    deduction_amount DECIMAL(10,2) DEFAULT 0.00,
    name VARCHAR(255) DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. CREATE TRAINING TABLE
CREATE TABLE training (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_title VARCHAR(255) NOT NULL,
    training_description TEXT NOT NULL,
    training_link VARCHAR(255),
    image_path VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- 11. ENABLE ROW LEVEL SECURITY (RLS) & PUBLIC ACCESS POLICIES
-- This allows the Supabase JavaScript client on GitHub / Vercel to read/write.
-- ==============================================================================

ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll ENABLE ROW LEVEL SECURITY;
ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE benefits ENABLE ROW LEVEL SECURITY;
ALTER TABLE benefits_deductions ENABLE ROW LEVEL SECURITY;
ALTER TABLE training ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read/Write Employees" ON employees FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Read/Write Attendance" ON attendance FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Read/Write Payroll" ON payroll FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Read/Write Announcements" ON announcements FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Read/Write Events" ON events FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Read/Write Feedback" ON feedback FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Read/Write Benefits" ON benefits FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Read/Write Deductions" ON benefits_deductions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Read/Write Training" ON training FOR ALL USING (true) WITH CHECK (true);

-- ==============================================================================
-- 12. INSERT INITIAL SEED DATA (from datamex_payroll_db.sql)
-- ==============================================================================

INSERT INTO employees ("employeeNo", password, "firstName", "lastName", "middleName", "birthDay", "birthPlace", address, email, gender, "civilStatus", nationality, religion, "phoneNumber", "sssNumber", "pagibigNumber", "tinNumber", "philhealthNumber", "bankAccount", "accountType", department, role, "dailyRate") VALUES
('2023009', '$2y$10$XyUFcjrsiQ0ZIPIKSrAb1uGO0/v.zDC524w03sSeB8YxrEsLd.WFK', 'MARCIAL LAWRENCE JR', 'CARONAN', 'VILLAGONZALO', '1997-08-30', 'PARANAQUE CITY', 'BLK 14 CRC PETCHAYAN, MULTINATIONAL VILLAGE, MOONWALK, PARANAQUE CITY', 'marcialcaronan@gmail.com', 'male', 'single', 'Filipino', 'Roman Catholic', '09202720151', '34-8291048-2', '1211-9384-2819', '312-849-102-000', '19-028391823-1', 'LandBank #1920-4820-19', 'admin', 'Information Technology', 'Lead Systems Architect & Full-Stack Developer', 750.00),
('2023039', '$2y$10$yn/Nali2yRw3nBozQUxMj.pReX89rbkhu.WMjQ8cOpFuT8lXSmiEG', 'Tyron John', 'Dela Cruz', 'Lucreda', '2004-09-04', 'Las Pinas', 'Las Pinas City', 'tyronjohn04@gmail.com', 'male', 'single', 'Filipino', 'Roman Catholic', '09234567281', '34-1029482-1', '1212-0948-1829', '291-840-192-000', '19-102948271-0', 'BDO #0012-3456-7890', 'admin', 'Human Resources', 'HR & Administrative Officer', 695.00),
('2023035', '$2y$10$4bB7.KFfL88e42LcoPJHVOdKpf7O7sveUYGELbhQ6oNZWCi/EovHW', 'Kerr', 'Pangan', 'Baliber', '2005-08-14', 'Paranaque', 'Paranaque City', 'kerr@gmail.com', 'male', 'single', 'Filipino', 'Catholic', '09202720151', '34-9281938-4', '1213-9482-7193', '381-920-482-000', '19-928172938-2', 'BPI #3829-1029-48', 'admin', 'Academic Affairs', 'Faculty Coordinator', 710.00),
('2024012', '$2y$10$ApmmxUQ2r5/VUzg41wAYn.Dyog7VYaRWtbppsQEtjoL6pDvM4BUWu', 'Rica Mhay', 'Saturinas', 'Castro', '2004-08-27', 'Paranaque', 'Paranaque City', 'ricamhaysaturinas2@gmail.com', 'female', 'single', 'Filipino', 'Catholic', '09123456789', '34-8192039-5', '1214-8291-0394', '482-910-381-000', '19-829103948-3', 'LandBank #1920-5829-33', 'employee', 'Admissions & Records', 'Registrar Staff', 695.00),
('2023024', '$2y$10$SNh/MQOsJDFa9sRBaBFTb.gB9uhZlZhFbahqKK9fTHh5gkVaNnVre', 'Jhay', 'Castro', 'Logatoc', '2004-12-30', 'Cavite', 'Paranaque City', 'cj5224751@gmail.com', 'male', 'single', 'Filipino', 'Roman Catholic', '09876565445', '34-0192847-9', '1215-9201-8374', '582-910-293-000', '19-019283746-5', 'Metrobank #2019-3829-11', 'admin', 'Operations', 'Facilities & Campus Supervisor', 700.00);

INSERT INTO attendance ("employeeNo", date, time_in, time_out, working_hours, late_minutes, overtime_hours, status) VALUES
('2023009', '2025-09-25', '08:00:00', '19:00:00', 8.00, 0, 2.00, 'Completed'),
('2023009', '2025-09-24', '08:00:47', '21:00:52', 8.00, 0, 4.00, 'Completed'),
('2023035', '2025-09-15', '08:00:08', '17:00:17', 8.00, 0, 0.00, 'Completed'),
('2024012', '2025-09-25', '19:17:57', '19:18:03', 0.00, 677, 0.00, 'Late Punch');

INSERT INTO payroll ("employeeNo", pay_period_start, pay_period_end, "ratePerHour", "hoursWorked", regular_days, "grossPay", deductions, "netPay", "payDate", "lateDeductions", overtime_hours) VALUES
('2023009', '2025-09-16', '2025-09-30', 93.75, 88.00, 11.00, 8953.13, 1940.00, 7013.13, '2025-10-06', 0.00, 6.00),
('2024012', '2025-09-01', '2025-09-15', 86.88, 80.00, 10.00, 6950.00, 1940.00, 5010.00, '2025-09-24', 0.00, 0.00);

INSERT INTO announcements (id, title, content, image_path, created_at) VALUES
(2, 'ROBLOX TOURNAMENT', 'PLAYER CAN PLAY - Official Collegiate Esports Championship for students and faculty.', 'uploads/announcement_68d422cd78bb71.99226635.png', '2025-09-24 16:56:45'),
(3, 'MIDTERM EXAMINATION SCHEDULE', 'All faculty members are advised to submit questionnaire drafts by Friday.', 'uploads/bg.jpg', '2025-09-26 09:30:00');

INSERT INTO events (id, event_name, event_date, event_location, image_path, created_at) VALUES
(1, 'Psychology & Wellness Seminar', '2025-10-15', 'Main Auditorium', 'uploads/event_690625a2e92372.41139206.jpg', '2025-09-23 16:07:30'),
(2, 'Foundation Day Collegiate Celebration', '2025-11-20', 'DCSA Sports Complex', 'uploads/recog.jpg', '2025-09-25 14:00:00');

INSERT INTO feedback (id, feedback_text, created_at) VALUES
(1, 'I love datamex college of saint adeline! The new kiosk portal makes time-in so much faster.', '2025-09-23 15:23:12'),
(2, 'Payroll calculations and automated payslips are very clear and helpful for faculty members.', '2025-09-24 10:14:05');

INSERT INTO benefits (id, benefit_title, benefit_details, created_at) VALUES
(1, 'SOCIAL SECURITY SYSTEM (SSS)', 'Mandatory social insurance program for private sector and academic personnel.', '2025-09-23 16:09:23'),
(2, 'PHILHEALTH HEALTHCARE', 'National health insurance program for medical coverage and hospitalization subsidies.', '2025-09-23 16:10:00'),
(3, 'PAG-IBIG HOME DEVELOPMENT MUTUAL FUND', 'Savings and affordable housing financing for educational staff.', '2025-09-23 16:11:00');

INSERT INTO benefits_deductions (id, benefit_name, deduction_amount, name) VALUES
(1, 'SSS Contribution', 1440.00, 'SSS Contribution'),
(2, 'Pag-IBIG Contribution', 100.00, 'Pag-IBIG Contribution'),
(3, 'PhilHealth Contribution', 400.00, 'PhilHealth Contribution'),
(4, 'TIN Withholding Tax', 0.00, 'TIN Withholding Tax');

INSERT INTO training (id, training_title, training_description, training_link, created_at) VALUES
(1, 'CSS NCII Certification Course', 'TESDA Computer Systems Servicing National Certificate II curriculum.', 'https://e-tesda.gov.ph/course/index.php?categoryid=16', '2025-09-23 16:08:57');
