const rawData = [
    {
        "Transaction_ID":  "T1000",
        "Day":  "1",
        "Day_of_Week":  "Mon",
        "Costumer_Age":  "29",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "5",
        "Printing_Pages":  "11",
        "Scanning_Pages":  "4",
        "Gaming":  "No",
        "Total_Sales":  "220"
    },
    {
        "Transaction_ID":  "T1001",
        "Day":  "2",
        "Day_of_Week":  "Tue",
        "Costumer_Age":  "22",
        "Gender":  "Female",
        "Student":  "Yes",
        "Internet_Hours":  "8",
        "Printing_Pages":  "0",
        "Scanning_Pages":  "7",
        "Gaming":  "No",
        "Total_Sales":  "270"
    },
    {
        "Transaction_ID":  "T1002",
        "Day":  "3",
        "Day_of_Week":  "Wed",
        "Costumer_Age":  "27",
        "Gender":  "Female",
        "Student":  "Yes",
        "Internet_Hours":  "7",
        "Printing_Pages":  "1",
        "Scanning_Pages":  "0",
        "Gaming":  "No",
        "Total_Sales":  "180"
    },
    {
        "Transaction_ID":  "T1003",
        "Day":  "4",
        "Day_of_Week":  "Thu",
        "Costumer_Age":  "18",
        "Gender":  "Female",
        "Student":  "No",
        "Internet_Hours":  "3",
        "Printing_Pages":  "2",
        "Scanning_Pages":  "6",
        "Gaming":  "Yes",
        "Total_Sales":  "205"
    },
    {
        "Transaction_ID":  "T1004",
        "Day":  "5",
        "Day_of_Week":  "Fri",
        "Costumer_Age":  "18",
        "Gender":  "Female",
        "Student":  "Yes",
        "Internet_Hours":  "1",
        "Printing_Pages":  "10",
        "Scanning_Pages":  "6",
        "Gaming":  "Yes",
        "Total_Sales":  "195"
    },
    {
        "Transaction_ID":  "T1005",
        "Day":  "6",
        "Day_of_Week":  "Sat",
        "Costumer_Age":  "19",
        "Gender":  "Female",
        "Student":  "Yes",
        "Internet_Hours":  "4",
        "Printing_Pages":  "10",
        "Scanning_Pages":  "1",
        "Gaming":  "No",
        "Total_Sales":  "160"
    },
    {
        "Transaction_ID":  "T1006",
        "Day":  "7",
        "Day_of_Week":  "Sun",
        "Costumer_Age":  "18",
        "Gender":  "Female",
        "Student":  "No",
        "Internet_Hours":  "3",
        "Printing_Pages":  "10",
        "Scanning_Pages":  "4",
        "Gaming":  "Yes",
        "Total_Sales":  "225"
    },
    {
        "Transaction_ID":  "T1007",
        "Day":  "8",
        "Day_of_Week":  "Mon",
        "Costumer_Age":  "29",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "4",
        "Printing_Pages":  "6",
        "Scanning_Pages":  "2",
        "Gaming":  "No",
        "Total_Sales":  "150"
    },
    {
        "Transaction_ID":  "T1008",
        "Day":  "9",
        "Day_of_Week":  "Tue",
        "Costumer_Age":  "18",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "1",
        "Printing_Pages":  "15",
        "Scanning_Pages":  "5",
        "Gaming":  "No",
        "Total_Sales":  "150"
    },
    {
        "Transaction_ID":  "T1009",
        "Day":  "10",
        "Day_of_Week":  "Wed",
        "Costumer_Age":  "33",
        "Gender":  "Female",
        "Student":  "Yes",
        "Internet_Hours":  "6",
        "Printing_Pages":  "0",
        "Scanning_Pages":  "5",
        "Gaming":  "No",
        "Total_Sales":  "200"
    },
    {
        "Transaction_ID":  "T1010",
        "Day":  "11",
        "Day_of_Week":  "Thu",
        "Costumer_Age":  "23",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "3",
        "Printing_Pages":  "14",
        "Scanning_Pages":  "6",
        "Gaming":  "No",
        "Total_Sales":  "205"
    },
    {
        "Transaction_ID":  "T1011",
        "Day":  "12",
        "Day_of_Week":  "Fri",
        "Costumer_Age":  "28",
        "Gender":  "Female",
        "Student":  "Yes",
        "Internet_Hours":  "4",
        "Printing_Pages":  "6",
        "Scanning_Pages":  "6",
        "Gaming":  "Yes",
        "Total_Sales":  "250"
    },
    {
        "Transaction_ID":  "T1012",
        "Day":  "13",
        "Day_of_Week":  "Sat",
        "Costumer_Age":  "33",
        "Gender":  "Male",
        "Student":  "No",
        "Internet_Hours":  "2",
        "Printing_Pages":  "10",
        "Scanning_Pages":  "4",
        "Gaming":  "No",
        "Total_Sales":  "140"
    },
    {
        "Transaction_ID":  "T1013",
        "Day":  "14",
        "Day_of_Week":  "Sun",
        "Costumer_Age":  "27",
        "Gender":  "Female",
        "Student":  "Yes",
        "Internet_Hours":  "3",
        "Printing_Pages":  "12",
        "Scanning_Pages":  "2",
        "Gaming":  "No",
        "Total_Sales":  "155"
    },
    {
        "Transaction_ID":  "T1014",
        "Day":  "15",
        "Day_of_Week":  "Mon",
        "Costumer_Age":  "30",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "7",
        "Printing_Pages":  "3",
        "Scanning_Pages":  "0",
        "Gaming":  "Yes",
        "Total_Sales":  "250"
    },
    {
        "Transaction_ID":  "T1015",
        "Day":  "16",
        "Day_of_Week":  "Tue",
        "Costumer_Age":  "18",
        "Gender":  "Male",
        "Student":  "No",
        "Internet_Hours":  "2",
        "Printing_Pages":  "5",
        "Scanning_Pages":  "7",
        "Gaming":  "No",
        "Total_Sales":  "145"
    },
    {
        "Transaction_ID":  "T1016",
        "Day":  "17",
        "Day_of_Week":  "Wed",
        "Costumer_Age":  "17",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "8",
        "Printing_Pages":  "1",
        "Scanning_Pages":  "3",
        "Gaming":  "No",
        "Total_Sales":  "235"
    },
    {
        "Transaction_ID":  "T1017",
        "Day":  "18",
        "Day_of_Week":  "Thu",
        "Costumer_Age":  "19",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "1",
        "Printing_Pages":  "10",
        "Scanning_Pages":  "2",
        "Gaming":  "No",
        "Total_Sales":  "95"
    },
    {
        "Transaction_ID":  "T1018",
        "Day":  "19",
        "Day_of_Week":  "Fri",
        "Costumer_Age":  "35",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "3",
        "Printing_Pages":  "8",
        "Scanning_Pages":  "3",
        "Gaming":  "No",
        "Total_Sales":  "145"
    },
    {
        "Transaction_ID":  "T1019",
        "Day":  "20",
        "Day_of_Week":  "Sat",
        "Costumer_Age":  "30",
        "Gender":  "Male",
        "Student":  "No",
        "Internet_Hours":  "1",
        "Printing_Pages":  "8",
        "Scanning_Pages":  "0",
        "Gaming":  "No",
        "Total_Sales":  "65"
    },
    {
        "Transaction_ID":  "T1020",
        "Day":  "21",
        "Day_of_Week":  "Sun",
        "Costumer_Age":  "34",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "2",
        "Printing_Pages":  "15",
        "Scanning_Pages":  "7",
        "Gaming":  "Yes",
        "Total_Sales":  "255"
    },
    {
        "Transaction_ID":  "T1021",
        "Day":  "22",
        "Day_of_Week":  "Mon",
        "Costumer_Age":  "32",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "3",
        "Printing_Pages":  "9",
        "Scanning_Pages":  "1",
        "Gaming":  "No",
        "Total_Sales":  "130"
    },
    {
        "Transaction_ID":  "T1022",
        "Day":  "23",
        "Day_of_Week":  "Tue",
        "Costumer_Age":  "33",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "8",
        "Printing_Pages":  "15",
        "Scanning_Pages":  "1",
        "Gaming":  "No",
        "Total_Sales":  "285"
    },
    {
        "Transaction_ID":  "T1023",
        "Day":  "24",
        "Day_of_Week":  "Wed",
        "Costumer_Age":  "27",
        "Gender":  "Female",
        "Student":  "Yes",
        "Internet_Hours":  "4",
        "Printing_Pages":  "11",
        "Scanning_Pages":  "1",
        "Gaming":  "No",
        "Total_Sales":  "165"
    },
    {
        "Transaction_ID":  "T1024",
        "Day":  "25",
        "Day_of_Week":  "Thu",
        "Costumer_Age":  "30",
        "Gender":  "Female",
        "Student":  "No",
        "Internet_Hours":  "2",
        "Printing_Pages":  "9",
        "Scanning_Pages":  "0",
        "Gaming":  "No",
        "Total_Sales":  "95"
    },
    {
        "Transaction_ID":  "T1025",
        "Day":  "26",
        "Day_of_Week":  "Fri",
        "Costumer_Age":  "29",
        "Gender":  "Female",
        "Student":  "Yes",
        "Internet_Hours":  "8",
        "Printing_Pages":  "15",
        "Scanning_Pages":  "3",
        "Gaming":  "Yes",
        "Total_Sales":  "365"
    },
    {
        "Transaction_ID":  "T1026",
        "Day":  "27",
        "Day_of_Week":  "Sat",
        "Costumer_Age":  "28",
        "Gender":  "Female",
        "Student":  "No",
        "Internet_Hours":  "8",
        "Printing_Pages":  "14",
        "Scanning_Pages":  "7",
        "Gaming":  "No",
        "Total_Sales":  "340"
    },
    {
        "Transaction_ID":  "T1027",
        "Day":  "28",
        "Day_of_Week":  "Sun",
        "Costumer_Age":  "35",
        "Gender":  "Female",
        "Student":  "Yes",
        "Internet_Hours":  "5",
        "Printing_Pages":  "15",
        "Scanning_Pages":  "3",
        "Gaming":  "No",
        "Total_Sales":  "230"
    },
    {
        "Transaction_ID":  "T1028",
        "Day":  "29",
        "Day_of_Week":  "Mon",
        "Costumer_Age":  "26",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "7",
        "Printing_Pages":  "3",
        "Scanning_Pages":  "0",
        "Gaming":  "No",
        "Total_Sales":  "190"
    },
    {
        "Transaction_ID":  "T1029",
        "Day":  "30",
        "Day_of_Week":  "Tue",
        "Costumer_Age":  "27",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "4",
        "Printing_Pages":  "14",
        "Scanning_Pages":  "4",
        "Gaming":  "No",
        "Total_Sales":  "210"
    },
    {
        "Transaction_ID":  "T1030",
        "Day":  "31",
        "Day_of_Week":  "Wed",
        "Costumer_Age":  "30",
        "Gender":  "Female",
        "Student":  "No",
        "Internet_Hours":  "4",
        "Printing_Pages":  "0",
        "Scanning_Pages":  "5",
        "Gaming":  "Yes",
        "Total_Sales":  "210"
    },
    {
        "Transaction_ID":  "T1031",
        "Day":  "32",
        "Day_of_Week":  "Thu",
        "Costumer_Age":  "34",
        "Gender":  "Female",
        "Student":  "No",
        "Internet_Hours":  "6",
        "Printing_Pages":  "14",
        "Scanning_Pages":  "3",
        "Gaming":  "Yes",
        "Total_Sales":  "310"
    },
    {
        "Transaction_ID":  "T1032",
        "Day":  "33",
        "Day_of_Week":  "Fri",
        "Costumer_Age":  "23",
        "Gender":  "Female",
        "Student":  "No",
        "Internet_Hours":  "7",
        "Printing_Pages":  "13",
        "Scanning_Pages":  "2",
        "Gaming":  "No",
        "Total_Sales":  "260"
    },
    {
        "Transaction_ID":  "T1033",
        "Day":  "34",
        "Day_of_Week":  "Sat",
        "Costumer_Age":  "31",
        "Gender":  "Female",
        "Student":  "Yes",
        "Internet_Hours":  "3",
        "Printing_Pages":  "6",
        "Scanning_Pages":  "7",
        "Gaming":  "Yes",
        "Total_Sales":  "235"
    },
    {
        "Transaction_ID":  "T1034",
        "Day":  "35",
        "Day_of_Week":  "Sun",
        "Costumer_Age":  "24",
        "Gender":  "Male",
        "Student":  "No",
        "Internet_Hours":  "8",
        "Printing_Pages":  "5",
        "Scanning_Pages":  "1",
        "Gaming":  "No",
        "Total_Sales":  "235"
    },
    {
        "Transaction_ID":  "T1035",
        "Day":  "36",
        "Day_of_Week":  "Mon",
        "Costumer_Age":  "32",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "5",
        "Printing_Pages":  "14",
        "Scanning_Pages":  "3",
        "Gaming":  "No",
        "Total_Sales":  "225"
    },
    {
        "Transaction_ID":  "T1036",
        "Day":  "37",
        "Day_of_Week":  "Tue",
        "Costumer_Age":  "23",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "5",
        "Printing_Pages":  "12",
        "Scanning_Pages":  "2",
        "Gaming":  "Yes",
        "Total_Sales":  "265"
    },
    {
        "Transaction_ID":  "T1037",
        "Day":  "38",
        "Day_of_Week":  "Wed",
        "Costumer_Age":  "21",
        "Gender":  "Female",
        "Student":  "Yes",
        "Internet_Hours":  "2",
        "Printing_Pages":  "4",
        "Scanning_Pages":  "7",
        "Gaming":  "No",
        "Total_Sales":  "140"
    },
    {
        "Transaction_ID":  "T1038",
        "Day":  "39",
        "Day_of_Week":  "Thu",
        "Costumer_Age":  "25",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "4",
        "Printing_Pages":  "8",
        "Scanning_Pages":  "4",
        "Gaming":  "Yes",
        "Total_Sales":  "240"
    },
    {
        "Transaction_ID":  "T1039",
        "Day":  "40",
        "Day_of_Week":  "Fri",
        "Costumer_Age":  "24",
        "Gender":  "Male",
        "Student":  "No",
        "Internet_Hours":  "1",
        "Printing_Pages":  "13",
        "Scanning_Pages":  "0",
        "Gaming":  "No",
        "Total_Sales":  "90"
    },
    {
        "Transaction_ID":  "T1040",
        "Day":  "41",
        "Day_of_Week":  "Sat",
        "Costumer_Age":  "33",
        "Gender":  "Female",
        "Student":  "Yes",
        "Internet_Hours":  "1",
        "Printing_Pages":  "15",
        "Scanning_Pages":  "1",
        "Gaming":  "No",
        "Total_Sales":  "110"
    },
    {
        "Transaction_ID":  "T1041",
        "Day":  "42",
        "Day_of_Week":  "Sun",
        "Costumer_Age":  "24",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "6",
        "Printing_Pages":  "0",
        "Scanning_Pages":  "6",
        "Gaming":  "No",
        "Total_Sales":  "210"
    },
    {
        "Transaction_ID":  "T1042",
        "Day":  "43",
        "Day_of_Week":  "Mon",
        "Costumer_Age":  "17",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "3",
        "Printing_Pages":  "4",
        "Scanning_Pages":  "2",
        "Gaming":  "No",
        "Total_Sales":  "115"
    },
    {
        "Transaction_ID":  "T1043",
        "Day":  "44",
        "Day_of_Week":  "Tue",
        "Costumer_Age":  "18",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "1",
        "Printing_Pages":  "2",
        "Scanning_Pages":  "5",
        "Gaming":  "No",
        "Total_Sales":  "85"
    },
    {
        "Transaction_ID":  "T1044",
        "Day":  "45",
        "Day_of_Week":  "Wed",
        "Costumer_Age":  "18",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "1",
        "Printing_Pages":  "2",
        "Scanning_Pages":  "5",
        "Gaming":  "No",
        "Total_Sales":  "85"
    },
    {
        "Transaction_ID":  "T1045",
        "Day":  "46",
        "Day_of_Week":  "Thu",
        "Costumer_Age":  "34",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "1",
        "Printing_Pages":  "12",
        "Scanning_Pages":  "7",
        "Gaming":  "No",
        "Total_Sales":  "155"
    },
    {
        "Transaction_ID":  "T1046",
        "Day":  "47",
        "Day_of_Week":  "Fri",
        "Costumer_Age":  "29",
        "Gender":  "Female",
        "Student":  "Yes",
        "Internet_Hours":  "1",
        "Printing_Pages":  "10",
        "Scanning_Pages":  "1",
        "Gaming":  "Yes",
        "Total_Sales":  "145"
    },
    {
        "Transaction_ID":  "T1047",
        "Day":  "48",
        "Day_of_Week":  "Sat",
        "Costumer_Age":  "32",
        "Gender":  "Female",
        "Student":  "Yes",
        "Internet_Hours":  "8",
        "Printing_Pages":  "0",
        "Scanning_Pages":  "6",
        "Gaming":  "No",
        "Total_Sales":  "260"
    },
    {
        "Transaction_ID":  "T1048",
        "Day":  "49",
        "Day_of_Week":  "Sun",
        "Costumer_Age":  "32",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "1",
        "Printing_Pages":  "7",
        "Scanning_Pages":  "7",
        "Gaming":  "Yes",
        "Total_Sales":  "190"
    },
    {
        "Transaction_ID":  "T1049",
        "Day":  "50",
        "Day_of_Week":  "Mon",
        "Costumer_Age":  "35",
        "Gender":  "Male",
        "Student":  "Yes",
        "Internet_Hours":  "4",
        "Printing_Pages":  "12",
        "Scanning_Pages":  "6",
        "Gaming":  "No",
        "Total_Sales":  "220"
    }
]
;
